language: java
script:
  - cd ${TRAVIS_BUILD_DIR}/${MODULE} && mvn test -B -Dmaven.test.redirectTestOutputToFile
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=1g -Xmx4g"
  matrix:
    - MODULE=matsim
    - MODULE=contribs
    - MODULE=playgrounds
