name: full-integration

on:
  schedule:
    - cron: '30 0 * * *' # daily at 0:30 UTC

jobs:
  code-coverage:
    name: run full integration

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Prepare git
        # turn off CRLF conversion (necessary on Windows)
        run: git config --global core.autocrlf false

      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'maven'

      # Run unit and integration tests
      - name: Run verify - release profile
        # arguments containing dots (.) need to be quoted ('') so that PowerShell (Windows) does not parse them
        run: mvn verify -P release --batch-mode --fail-at-end -D'maven.test.redirectTestOutputToFile' -D'matsim.preferLocalDtds=true'

    env:
      MAVEN_OPTS: -Xmx2g
