name: test-integration.yaml
on: push

jobs:
  run-integration:
    timeout-minutes: 10
    name: test integration

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Prepare git
        # turn off CRLF conversion (necessary on Windows)
        run: git config --global core.autocrlf false

      - name: Checkout git repo
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'zulu'
          cache: 'maven'

      - name: Build reactor
        run: mvn -pl contribs/distributed-simulation -am install -P release --batch-mode --fail-at-end -D'matsim.preferLocalDtds=true' -DskipTests

      # Run unit and integration tests
      - name: Run verify - release profile
        # arguments containing dots (.) need to be quoted ('') so that PowerShell (Windows) does not parse them]
        run: mvn -pl contribs/distributed-simulation test -P release --batch-mode --fail-at-end -D'matsim.preferLocalDtds=true' -Dtest=ThreeLinkIntegrationTest

      - name: Upload Maven test reports
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports-${{ matrix.os }}
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
            **/target/*-reports/**
          if-no-files-found: warn
    env:
      MAVEN_OPTS: -Xmx2g
