name: verify-push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module:
          - matsim
          # sorted from longest to shortest (to minimise the overall test stage duration)
          # (used in travis; not respected in GitHub Action workflows)
          - contribs/vsp
          - contribs/common
          - contribs/taxi
          - contribs/minibus
          - contribs/signals
          - contribs/bicycle
          - contribs/cadytsIntegration
          - contribs/drt
          - contribs/discrete_mode_choice
          - contribs/carsharing
          - contribs/commercialTrafficApplications
          - contribs/av
          - contribs/locationchoice
          - contribs/ev
          - contribs/dvrp
          - contribs/emissions
          - contribs/decongestion
          - contribs/noise
          - contribs/accidents
          - contribs/freight
          - contribs/parking
          - contribs/matrixbasedptrouter
          - contribs/accessibility
          - contribs/integration
          - contribs/multimodal
          - contribs/protobuf
          - contribs/socnetsim
          - contribs/sumo
          - contribs/pseudosimulation
          - contribs/roadpricing
          - contribs/analysis
          - contribs/eventsBasedPTRouter
          - contribs/hybridsim
          - contribs/otfvis
          - contribs/osm

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Detect changes against master
        # we only want to build matsim (module) if changes are not limited to contribs
        id: detect-changes
        uses: dorny/paths-filter@v2
        if: ${{matrix.module == 'matsim'}}
        with:
          filters: |
            outside-contribs:
              - '!contribs/**'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        if: ${{matrix.module != 'matsim' || steps.detect-changes.outputs.outside-contribs == 'true'}}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        if: ${{matrix.module != 'matsim' || steps.detect-changes.outputs.outside-contribs == 'true'}}
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build module (with dependencies)
        if: ${{matrix.module != 'matsim' || steps.detect-changes.outputs.outside-contribs == 'true'}}
        run: mvn install --batch-mode --also-make --projects ${{matrix.module}} -DskipTests -Dmaven.javadoc.skip -Dsource.skip -Dassembly.skipAssembly=true

      - name: Test module
        if: ${{matrix.module != 'matsim' || steps.detect-changes.outputs.outside-contribs == 'true'}}
        run: mvn verify --batch-mode -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end -Dmaven.javadoc.skip -Dsource.skip -Dassembly.skipAssembly=true
        working-directory: ${{matrix.module}}

    env:
      MAVEN_OPTS: -Xmx2g

